### ISSUE TITLE
ComponentKit uses API unsafe in extensions

### ISSUE THREAD

**Issue by nickfrey** [facebook/componentkit#390]
ComponentKit uses `[UIApplication sharedApplication]` in three places.

https://github.com/facebook/componentkit/blob/cc3cfac0b420fc8a635825a9c39022a10e4af818/ComponentKit/Debug/CKComponentHierarchyDebugHelper.mm#L39
https://github.com/facebook/componentkit/blob/fbab23010ab15cba8ef934289a32d1a650e7e713/ComponentKit/Debug/CKComponentDebugController.mm#L141
https://github.com/facebook/componentkit/blob/c919686da3d8bb76009f2ebc437108b25ac628d9/ComponentTextKit/Utility/CKAsyncTransactionGroup.m#L82

If this API usage could be avoided, Xcode wouldn't complain about ComponentKit being unsafe for use in extensions. The first two cases are nonessential and could be resolved by just using `performSelector:@selector(sharedApplication)` but I'm not sure about `CKAsyncTransactionGroup`. Anyone have thoughts on this?

**Comment by adamjernst** [comment]
Good find. Sure, let me take a look.

**Comment by conradev** [comment]
This should be fixed by #534, all extension unsafe APIs are now marked as such.

**Comment by eczarny** [comment]
I think we're still missing an unsafe API in `CKComponentHierarchyDebugHelper`. We should mark `+[CKComponentHierarchyDebugHelper componentHierarchyDescription]` as unsafe as well.
